- name: PLAY-1
  hosts: Localhost
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: hello from play-1 and task-1

- name: PLAY-2
  hosts: Localhost
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      msg: hello from play-2 and task-2
      