# task level variables
- name: task levelplaybooks
  hosts: localhost
  vars:
    Course: "Devops"
    Learner: "sridevi"
    Duration: "3-months"
  tasks:
  - name: check task levelvariables
    vars: # task level
      Course: "Devops with aws"
    ansible.builtin.debug:
      msg: "hi, im learning {{Course}}, learner is {{Learner}}, and duration is {{Duration}}"    