- name: variables from prefernce level plsybook
  hosts: localhost
  vars_files:
  - variables-files.yaml 
  # vars_prompt:
  # - name: Person
  #   prompt: Please enter your name
  #   private: false #user can see what they are entering
  # - name: Wishes
  #   prompt: please enter your wishes
  #   private: false  #user cant see what they are entering
  # vars:
  #   Person: "sridevi from play"
  #   Wishes: "good from play"
  tasks:
  - name: vars from directly applying from prefernce level variable
    # vars:
    #   Person: "sridevi from tasks"
    #   Wishes: "good from tasks"
    ansible.builtin.debug:
      msg: "Hi, Im learning {{Person}}, learner is {{Wishes}}"


# first prefernce from command {CMD} ---CMD
# second prefernce tasks level  --- TASK LEVEL
# third prefernce from file level vars--FILE LEVEL
# fourth prefernce from prompt---- PROMPT LEVEL
# fifth prefernce form play level ---PLAY LEVEL