- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.debug:
      name: "{{item}}" # item is the default keyword in loop
      state: present
    loop:
    - git
    - mysql
    - postfix
    - nodejs
     
